gantt
    title Příklad zobrazení všech rezervací
    dateFormat  YYYY-MM-DD HH:mm
    axisFormat  %H:%M

    section Agent A
    Reservation 1 :a1, 2026-09-21 09:00, 60m
    Reservation 2 :a2, 2026-09-21 11:00, 90m

    section Agent B
    Reservation 3 :b1, 2026-09-21 09:30, 120m

    section Agent C
    Reservation 4 :c1, 2026-09-21 12:00, 60m
